# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-17 01:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0001_initial'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=150)),
                ('body', models.TextField(default=None)),
                ('formatted_body', models.TextField(default=None)),
                ('excerpt', models.CharField(default=None, max_length=255)),
                ('slug', models.CharField(default='2cb5547b-7333-4ea1-a915-661d7b64e294', max_length=255)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('date_of_last_changes', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Published', 'Published'), ('Trashed', 'Trashed')], default='Pending', max_length=100)),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comments', models.ManyToManyField(related_name='comments', to='comments.Comment')),
                ('tags', models.ManyToManyField(related_name='tags', to='tags.Tag')),
                ('thumbnail', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_library.Media')),
            ],
        ),
    ]
