# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-17 01:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=150)),
                ('slug', models.CharField(default='178aebdd-7604-4f6f-80da-6f85a26104a4', max_length=150)),
                ('description', models.TextField(default=None)),
                ('country', models.CharField(default=None, max_length=150)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Published', 'Published'), ('Trashed', 'Trashed')], default='Pending', max_length=100)),
                ('banner', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner', to='media_library.Media')),
                ('thumbnail', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thumbnail', to='media_library.Media')),
            ],
        ),
    ]
