FROM python:3.5

RUN mkdir /app

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y

ADD . /app

RUN pip install -r /app/requirments.txt && chmod +x /app/entrypoint-celery-worker.sh && chmod +x /app/entrypoint-worker.sh

VOLUME ["/app"]
WORKDIR /app
ENV PYTHONUNBUFFERED 1
