FROM python:3.4
 ENV PYTHONUNBUFFERED 1
 RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y \
    npm \
    nodejs-legacy

 ADD . /salarium
 RUN pip install -r /salarium/requirments.txt && npm install -g bower && npm install -g grunt-cli && npm install grunt -g && cd /salarium && npm install && bower install --allow-root

 VOLUME ["/salarium"]
 WORKDIR /salarium