# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-17 01:01
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=254, unique=True)),
                ('name', models.CharField(default=None, max_length=254, null=True)),
                ('surname', models.CharField(default=None, max_length=254, null=True)),
                ('patronymic', models.CharField(default=None, max_length=254, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, default=None, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number invalid.', regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.CharField(default=None, max_length=254, null=True)),
                ('house', models.CharField(default=None, max_length=254, null=True)),
                ('housing_number', models.CharField(default=None, max_length=254, null=True)),
                ('flat_number', models.CharField(default=None, max_length=254, null=True)),
                ('post_index', models.CharField(default=None, max_length=254, null=True)),
                ('is_team', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('include_in_email_delivery', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('last_activity_ip', models.GenericIPAddressField()),
                ('last_activity_date', models.DateTimeField(default=datetime.datetime(1950, 1, 1, 0, 0))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='thumbnail',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_thumbnail', to='media_library.Media'),
        ),
    ]
