"""
Django settings for salarium project.

Generated by 'django-admin startproject' using Django 1.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
import cloudinary

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '=vd01es$v#u6ct8#7u9mht%)f59dm6ih1*0bq*s=*ov+$a0#rc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['salarium.tk', 'salarium.by', 'salarium.com', 'localhost', '127.0.0.1']

AUTH_USER_MODEL = 'customer.Customer'
LAZYSIGNUP_USER_MODEL = 'customer.Customer'

SESSION_COOKIE_AGE = 60 * 60 * 24 * 30

VK_SECURE_TOKEN = '2515a3af2515a3af2515a3af4c254e3d97225152515a3af7c1544d26d767ee6cb96e6d9'
VK_APP_ID = 6004280
VK_ADMIN_EMAIL = 's5deeex@gmail.com'
VK_ADMIN_PASSWORD = 'astonmartin1990'
VK_GROUP_ID = 42000547
VK_ALBUM_ID = 243921958

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'authentication',
    'customer',
    'news',
    'comments',
    'categories',
    'blog',
    'posts',
    'cloudinary',
    'media_library',
    'tags',
    'brand',
    'item',
    'slider',
    'shop',
    'notifications',
    'basket',
    'emails',
    'mathfilters',
    'settings',
    'channels',
    'chat',
    'storages',
    'djcelery',
    'queued_storage',
    'lazysignup'
]

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "asgi_redis.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("redis", 6379)],
        },
        "ROUTING": "chat.routing.channel_routing",
    },
}

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.RemoteUserMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'salarium.middleware.LastActivityMiddleware',
]
ROOT_URLCONF = 'salarium.urls'
STATIC_ROOT = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

cloudinary.config(
    cloud_name="salarium",
    api_key="955711257559496",
    api_secret="1OKZbPLi7z5iLW3VS7sj-Uzs_f4"
)

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'salarium.wsgi.application'


DATE_FORMAT = 'j F Y'
TIME_FORMAT = 'H:i'
DATETIME_FORMAT = 'j F Y H:i'
YEAR_MONTH_FORMAT = 'F Y'
MONTH_DAY_FORMAT = 'j F'
SHORT_DATE_FORMAT = 'j N Y'
SHORT_DATETIME_FORMAT = 'j N Y H:i'
FIRST_DAY_OF_WEEK = 1

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'docker',
        'USER': 'docker',
        'PASSWORD': 'docker',
        'HOST': 'db',
        'PORT': 3306,
    }
}


# CELERY
import djcelery
djcelery.setup_loader()

CELERY_RESULT_BACKEND = "redis"
CELERY_REDIS_HOST = "redis"
CELERY_REDIS_PORT = 6379
CELERY_REDIS_DB = 0
CELERY_TASK_RESULT_EXPIRES = 10
CELERY_SEND_EVENTS = True

BROKER_HOST = "redis"
BROKER_BACKEND = "redis"
BROKER_URL = "redis://redis:6379/0"

CELERY_IMPORTS = ('salarium.tasks',)


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.RemoteUserBackend',
    'django.contrib.auth.backends.ModelBackend',
    'customer.backends.CustomerAuthBackend',
    'lazysignup.backends.LazySignupBackend'
]

# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# email send config
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'go.events.app@gmail.com'
EMAIL_HOST_PASSWORD = 'goevents11'
EMAIL_PORT = 587
