# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-17 01:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default='68c28b3c-278e-4632-aeb7-4e7c1beb85ff', max_length=150)),
                ('type', models.CharField(choices=[('CommentAdded', 'CommentAdded'), ('CommentUpdated', 'CommentUpdated'), ('TransactionCanceled', 'TransactionCanceled'), ('TransactionCompleted', 'TransactionCompleted'), ('TransactionCreated', 'TransactionCreated'), ('TransactionProcessed', 'TransactionProcessed'), ('TransactionOrdersSend', 'TransactionSend')], default=None, max_length=150)),
                ('status', models.CharField(choices=[('Actual', 'Actual'), ('Viewed', 'Viewed')], default='Actual', max_length=150)),
                ('scope', models.CharField(choices=[('Admin', 'Admin'), ('System', 'System'), ('User', 'User')], default='System', max_length=150)),
                ('description', models.TextField(default='')),
                ('entity_pk', models.IntegerField(default=None, null=True)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
