# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-17 01:01
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default='f2184ea2-4596-4a7b-a4e8-fcbf803e193a', max_length=150)),
                ('count', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='item.Item')),
                ('items_sizes_count', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='item.ItemSizeCountMap')),
                ('purchaser', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default='415c7a6a-08e8-445c-9df6-e7ddc54facfa', max_length=150)),
                ('description', models.CharField(default=None, max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=None, max_length=150)),
                ('value', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default='886ae800-d232-4e2e-9c48-6f1aedfc594c', max_length=150)),
                ('transaction_code', models.CharField(default='DIAF00001', max_length=150)),
                ('status', models.CharField(choices=[('Canceled', 'Canceled'), ('Completed', 'Completed'), ('Created', 'Created'), ('PayConfirmed', 'PayConfirmed'), ('PayDecline', 'PayDecline'), ('PayFail', 'PayFail'), ('Pending', 'Pending'), ('Sent', 'Sent')], default='Created', max_length=150)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('orders', models.ManyToManyField(default=None, related_name='transaction', to='basket.Order')),
                ('purchaser', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default='cc7e992e-5937-42fa-b695-628f6f908081', max_length=150)),
                ('purchaser_name', models.CharField(default=None, max_length=254)),
                ('purchaser_surname', models.CharField(default=None, max_length=254)),
                ('purchaser_patronymic', models.CharField(default=None, max_length=254)),
                ('purchaser_email', models.EmailField(blank=True, max_length=254)),
                ('purchaser_phone_number', models.CharField(blank=True, default=None, max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number invalid.', regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.CharField(default=None, max_length=254)),
                ('city', models.CharField(default=None, max_length=254)),
                ('house', models.CharField(default=None, max_length=254)),
                ('housing_number', models.CharField(default=None, max_length=254)),
                ('flat_number', models.CharField(default=None, max_length=254)),
                ('post_index', models.CharField(default=None, max_length=254)),
                ('comment', models.CharField(default=None, max_length=554)),
                ('delivery_type', models.CharField(choices=[('CourierMinsk', 'CourierMinsk'), ('CourierMinsk', 'CourierVitebsk'), ('Post', 'Post')], default='Post', max_length=150)),
                ('payment_type', models.CharField(choices=[('COD', 'COD'), ('Cash', 'Cash'), ('CreditCard', 'CreditCard'), ('Erip', 'ERIP')], default='Cash', max_length=150)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('track_code', models.CharField(default=None, max_length=128, null=True)),
                ('credit_card_token', models.CharField(default=None, max_length=554, null=True)),
                ('promo_code', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_details', to='basket.PromoCode')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDiscounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_name', models.CharField(default='Sale', max_length=150)),
                ('discount_type', models.CharField(choices=[('PromoCode', 'PromoCode'), ('Sale', 'Sale')], default='Sale', max_length=150)),
                ('discount_value', models.IntegerField(default=0)),
                ('discount_rate', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_discount', to='basket.Order')),
                ('transaction', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_discounts', to='basket.Transaction')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_details',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='basket.TransactionDetails'),
        ),
    ]
