# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-17 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=150)),
                ('description', models.TextField(default=None, null=True)),
                ('public_id', models.IntegerField(default=None)),
                ('thumb_id', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=None, max_length=150)),
                ('album_id', models.CharField(default=None, max_length=150)),
                ('secure_url', models.CharField(default=None, max_length=255, null=True)),
                ('signature', models.CharField(default=None, max_length=255, null=True)),
                ('src_url', models.CharField(default=None, max_length=255, null=True)),
                ('version', models.CharField(default=None, max_length=255, null=True)),
                ('resource_type', models.CharField(default='image', max_length=255)),
                ('format', models.CharField(default=None, max_length=255, null=True)),
                ('from_vk', models.BooleanField(default=False)),
                ('photo_75', models.CharField(default=None, max_length=255, null=True)),
                ('photo_130', models.CharField(default=None, max_length=255, null=True)),
                ('photo_604', models.CharField(default=None, max_length=255, null=True)),
                ('photo_807', models.CharField(default=None, max_length=255, null=True)),
                ('photo_1280', models.CharField(default=None, max_length=255, null=True)),
                ('photo_2560', models.CharField(default=None, max_length=255, null=True)),
                ('description', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='photos',
            field=models.ManyToManyField(related_name='albums', to='media_library.Media'),
        ),
    ]
